---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{.Release.Name}}
spec:
  selector:
    matchLabels:
      app: {{.Release.Name}}
  template:
    metadata:
      labels:
        app: {{.Release.Name}}
    spec:
      containers:
      - name: driver
        image: {{.Values.driverImage}}
        imagePullPolicy: Never
        securityContext:
          privileged: true
        workingDir: /run/csi
        volumeMounts:
        - name: plugin-dir
          mountPath: /run/csi
        - name: mountpoint-dir
          mountPath: /var/lib/kubelet/
          mountPropagation: Bidirectional
        env:
        - name: RUST_LOG
          value: "info"
      - name: registrar
        image: {{.Values.registarImage}}
        aryo
        - --kubelet-registration-path=/var/lib/kubelet/plugins/shards.driver/socket
        volumeMounts:
        - name: plugin-dir
          mountPath: /run/csi
        - name: registration-dir
          mountPath: /registration
      volumes:
      - name: registration-dir
        hostPath:
          path: /var/lib/kubelet/plugins_registry/
          type: Directory
      - name: mountpoint-dir
        hostPath:
          path: /var/lib/kubelet/
          type: Directory
      - name: plugin-dir
        hostPath:
          path: /var/lib/kubelet/plugins/shards.driver/
          type: DirectoryOrCreate
